### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by Geant200** [shobhit-pathak/MatchZy#187] opened 2024-07-04 13:39 UTC
Hello, I noticed something, I don't know if it's a bug or a configuration error.

When I start a match I noticed that the money we receive is not the same on the main interface and on the scoreboard he adds the number 9 at the bottom left in the indication of the money.

CSS : counterstrikesharp-with-runtime-build-246-windows-a87bd25
MatchZy : MatchZy-0.7.12-with-cssharp-windows
Metamod : 2.0/1293

![money1](https://github.com/shobhit-pathak/MatchZy/assets/15239514/ea9136a8-f7b6-4658-b49d-ea790be35018)
![money2](https://github.com/shobhit-pathak/MatchZy/assets/15239514/d6c80e4b-0ab4-42e9-aa21-f77b9fe62238)
![money3](https://github.com/shobhit-pathak/MatchZy/assets/15239514/7412ecd3-f383-430d-81db-e2c643caae0a)
![money4](https://github.com/shobhit-pathak/MatchZy/assets/15239514/f470319c-27f5-4e5b-8b99-7e855373535f)

thank you in advance.

**Comment by shobhit-pathak** [comment] 2024-07-04 13:46
Hey!

This is weird, I don't think plugin is causing this issue as money is not changed in a live match.
Are you facing this issue withou MatchZy plugin? Or is there any other plugin which can cause this issue?
A wild guess, but this can be an issue with CS2 also. It can be an issue of the language that you're using in CS2, can you check if this looks fine in English?

**Comment by Geant200** [comment] 2024-07-04 14:38
I removed the MatchZy plugin and I don't have the bug.

![money5](https://github.com/shobhit-pathak/MatchZy/assets/15239514/7517bd47-6b64-42e9-a488-c000c04351bd)
![money6](https://github.com/shobhit-pathak/MatchZy/assets/15239514/e3aca6aa-9606-45cb-8a6a-5250cfdc38e4)
![money7](https://github.com/shobhit-pathak/MatchZy/assets/15239514/1a315a22-24de-474b-a4b8-22bdcb5c7331)
![money8](https://github.com/shobhit-pathak/MatchZy/assets/15239514/10b5cae7-530d-4ba6-98f3-1d464ad4fe5f)

**Comment by Geant200** [comment] 2024-07-04 14:46
I reinstalled the MatchZy plugin.
![money9](https://github.com/shobhit-pathak/MatchZy/assets/15239514/d54c62b1-7bc4-4b74-9108-b673c7f7e753)

**Comment by Geant200** [comment] 2024-07-05 17:35
Good morning.

I have just tested your version of the plugin, there are no bugs under the version of (counterstrikesharp-with-runtime-build-244-windows-7f5103d).

But when I use the latest version of (counterstrikesharp-with-runtime-build-247-windows-f8451c2) the bug appears.

Your plugin is experiencing bugs with the latest counterstrikesharp version.

Can you check.

**Comment by mrc4tt** [comment] 2024-07-06 18:22
Hey @Geant200 

Can you tell me (step by step) when the money is bugged? I will try debug it for you :-) /Miksen

**Comment by Geant200** [comment] 2024-07-06 19:42
I just retested with the latest version of (counterstrikesharp-with-runtime-build-247-windows-f8451c2)

The bug has disappeared, I will do some tests and if it happens again I will report back to you ^^.

Thanks ^^.

**Comment by shobhit-pathak** [comment] 2024-07-08 12:04
Hey!

Closing this issue since this is not reproducing now, you can open this if you feel this issue still persists.

**Closed by shobhit-pathak** 2024-07-08 12:04 UTC
