### ISSUE TITLE
Fatal error insert match data

### ISSUE THREAD

**Issue by OneDollarMan** [shobhit-pathak/MatchZy#130] opened 2024-04-08 10:12 UTC
Hello, everything was working, I tested a lot of matches, but then after another match I received this error, so match data wasn't saved to table matchzy_stats_matches:
<img width="978" alt="Снимок экрана 2024-04-05 в 19 09 11" src="https://github.com/shobhit-pathak/MatchZy/assets/52624425/c5ab881c-78ce-40fb-83b2-70be4a0700a1">
But on init stage everything was ok, database connected successfully. Why this was happened and how to fix this?

**Comment by shobhit-pathak** [comment] 2024-04-28 05:16
Hey!

This seems like the connection to the database was broken hence you were getting this error.
I think there is nothing that can be done from plugin side.

Thanks!

**Comment by shobhit-pathak** [comment] 2024-08-25 08:53
Hey!

Closing this issue as the issue is with database and not with the plugin. Thanks!

**Closed by shobhit-pathak** 2024-08-25 08:53 UTC
